# Generated by Django 4.0.6 on 2022-07-10 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShortUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_url', models.URLField(verbose_name='url')),
                ('url', models.URLField(verbose_name='key')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='urls',
            field=models.ManyToManyField(blank=True, null=True, related_name='urls', to='mainapp.shorturl'),
        ),
    ]
