# Generated by Django 4.0.6 on 2022-07-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_shorturl_user_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='url',
            field=models.URLField(verbose_name='url'),
        ),
    ]
