# Generated by Django 4.0.6 on 2022-07-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_shorturl_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='target_url',
            field=models.URLField(verbose_name='target_url'),
        ),
    ]
